theme = "docuapi"
languageCode = "en-us"
baseurl = "https://docs.tinydevcrm.com"
title = "TinyDevCRM API Documentation"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"

[module]
[module.hugoVersion]
[[module.imports]]
# We include the theme by "../.." above, but we need one module import for Hugo to detect us as a Hugo Module.
path="github.com/bep/empty-hugo-module"

[params]
search = false

# Configure the language example tabs.
[[params.language_tabs]]
key = "shell"
name = "Shell"

#Languages
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "DocuAPI Example Site"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [
"[Homepage](https://tinydevcrm.com)",
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true
